### ISSUE TITLE
can u help me?

### ISSUE THREAD

**Issue by Nemra1** [BackIsBachus/Rocket.Chat.Update.Script#1]
thx for ur great script its help me ..
i need help for ...
1- setup developer version..
2-commandline to build my owne customize

**Comment by BackIsBachus** [comment]
Hello (and sorry for the delay, I must have missed the notification on this issue),

Unfortunately I'm afraid I'm can't be of much help here since this script only purpose is to update an already running production RocketChat instance drom the already built sources at a small scale (eg. all on the same server, not many users, no heavy automation already in place and no real use for it).
Therefore doing a developer build is not really the focus of this small script.
